import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Frontend Engineer",
    company: "PT Delameta Bilano",
    logo: null,
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2025-01",
    end_date: null,
    industry: "Technology",
    link: null,
    responsibilities: [
      "Develop web-based applications using React.js and Vue.js to accelerate feature delivery through reusable components.",
      "Build dashboard systems with REST API integration to present operational data accurately and efficiently.",
      "Manage client-server communication flows to keep application state and backend data synchronized reliably.",
      "Debug and optimize application performance in production-facing workflows.",
      "Collaborate end-to-end with product and engineering teams to deliver web features faster.",
    ],
    lessons_learned: [
      "Strengthened frontend architecture decisions for operational dashboards and reusable UI systems.",
      "Improved API integration discipline, data synchronization handling, and production debugging practices.",
    ],
    impact: [
      "Improved feature development efficiency by approximately 30% through reusable component patterns.",
      "Increased operational data access speed by approximately 25% via dashboard and API integration improvements.",
      "Reduced production bugs by approximately 20% through debugging and performance optimization.",
    ],
    isShow: true,
  },
  {
    position: "Electronic Researcher",
    company: "PT Delameta Bilano",
    logo: null,
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2023-10",
    end_date: "2025-01",
    industry: "Electronics & IoT Research",
    link: null,
    responsibilities: [
      "Provided technical support for electronic systems by diagnosing and resolving hardware and software issues.",
      "Contributed to the development and testing of multiple prototypes across electronics and IoT initiatives.",
      "Worked across hardware-software integration flows to improve system interoperability and implementation speed.",
      "Developed IoT-oriented unit tests using Python, Flask, HTML, and CSS.",
    ],
    lessons_learned: [
      "Built stronger troubleshooting habits across embedded systems, electronics, and backend-connected IoT workflows.",
      "Expanded experience in prototyping, validation, and translating field issues into technical improvements.",
    ],
    impact: [
      "Increased system reliability by approximately 30% through diagnosis and resolution of hardware/software issues.",
      "Improved durability and reliability across more than 5 prototypes by approximately 30%.",
      "Reduced system integration time by approximately 25% through effective cross-functional collaboration.",
      "Lowered IoT system failure rate by approximately 15% via test coverage and critical bug identification.",
    ],
    isShow: true,
  },
  {
    position: "Backend Development Intern",
    company: "PT Batu Tala Saudara",
    logo: null,
    location: "Surabaya, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2024-11",
    end_date: "2024-12",
    industry: "EdTech / Self Development Platform",
    link: null,
    responsibilities: [
      "Contributed to the SuXesstories platform, a psychotest and self-development application for users aged 18+.",
      "Optimized job fair registration using QR code self-registration flows.",
      "Worked on frontend features with Vue.js and backend integration with Firebase and Express.js.",
      "Helped identify user onboarding issues and supported registration flow automation improvements.",
      "Assisted in writing technical documentation and user guidance for delivered features.",
    ],
    lessons_learned: [
      "Gained practical experience balancing backend contribution with user-facing workflow improvements.",
      "Learned how event-oriented product constraints shape registration, onboarding, and documentation priorities.",
    ],
    impact: [
      "Improved the job fair registration experience through QR-based onboarding flow enhancements.",
      "Contributed to documentation and platform changes that increased implementation efficiency by approximately 20% during event execution.",
    ],
    isShow: true,
  },
];
