import { EducationProps } from "../types/education";

export const EDUCATION: EducationProps[] = [
  {
    school: "Universitas Bina Bangsa",
    major: "Computer Science",
    logo: null,
    location: "Serang, Banten, Indonesia 🇮🇩",
    degree: "Bachelor's Degree",
    GPA: "3.63/4.00",
    start_year: 2021,
    end_year: 2025,
    link: "https://www.unibba.ac.id/",
    highlights: [
      "Graduate of Computer Science program with a strong foundation in software engineering, systems, and applied computing.",
    ],
    coursework: [
      "Data Structures & Algorithms",
      "Object-Oriented Programming",
      "Software Engineering",
      "DBMS",
      "Web Development",
      "Operating Systems",
      "Computer Networks",
      "Data Science",
      "Machine Learning",
      "Artificial Intelligence",
      "Mobile Development",
      "Cloud Computing",
      "IoT Fundamentals",
      "Software Testing & QA",
    ],
  },
  {
    school: "Maxy Academy",
    major: "Rapid Application Backend Bootcamp",
    logo: null,
    location: "Indonesia",
    degree: "Bootcamp",
    start_year: 2024,
    end_year: 2024,
    link: "https://maxy.academy/",
    highlights: [
      "Completed the program with 100% student learning progress between September 2024 and December 2024.",
    ],
    coursework: [
      "Database Management & Optimization",
      "Rapid Development with Laravel",
      "Bootstrap 4 & Semantic UI",
      "jQuery UI",
      "LeafletJS",
      "DataTables",
      "PHPSpreadsheet",
      "HTML, CSS, JavaScript",
      "Lumen Web Services",
      "Web Scraping",
      "Social OAuth",
      "Two-Factor Authentication",
      "SEO Management",
      "Python Fundamentals",
      "Data Mining",
    ],
  },
];
