-- Schema setup for the Supabase resources used by this project.
-- Run this file first, then run supabase/seed.sql.

create extension if not exists "pgcrypto";

create type public.achievement_type as enum (
  'Course',
  'Certification',
  'Award',
  'Bootcamp',
  'Competition',
  'Workshop',
  'Scholarship',
  'Other'
);

create type public.achievement_category as enum (
  'Backend',
  'Frontend',
  'Mobile',
  'DevOps',
  'Cloud',
  'Data',
  'AI',
  'General'
);

create or replace function public.get_enum_values(type_name text)
returns table (enum_value text)
language sql
stable
as $$
  select e.enumlabel::text
  from pg_type t
  join pg_enum e on t.oid = e.enumtypid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
    and t.typname = type_name
  order by e.enumsortorder;
$$;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text not null,
  link_demo text,
  link_github text,
  stacks text[] not null default '{}',
  is_show boolean not null default true,
  is_featured boolean not null default false
);

create index if not exists projects_slug_idx on public.projects (slug);
create index if not exists projects_is_show_idx on public.projects (is_show);
create index if not exists projects_is_featured_idx on public.projects (is_featured);

create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  credential_id text,
  slug text not null unique,
  name text not null,
  issuing_organization text not null,
  type public.achievement_type not null,
  category public.achievement_category not null,
  url_credential text,
  issue_date date not null,
  expiration_date date,
  is_show boolean not null default true
);

create index if not exists achievements_slug_idx on public.achievements (slug);
create index if not exists achievements_name_idx on public.achievements (name);
create index if not exists achievements_category_idx on public.achievements (category);
create index if not exists achievements_type_idx on public.achievements (type);
create index if not exists achievements_is_show_idx on public.achievements (is_show);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  image text,
  message text not null,
  is_reply boolean not null default false,
  reply_to text,
  is_show boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages (created_at);
create index if not exists messages_is_show_idx on public.messages (is_show);
create index if not exists messages_email_idx on public.messages (email);

alter table public.projects disable row level security;
alter table public.achievements disable row level security;
alter table public.messages disable row level security;

insert into storage.buckets (id, name, public)
values
  ('projects', 'projects', true),
  ('achievements', 'achievements', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public read projects bucket" on storage.objects;
create policy "Public read projects bucket"
on storage.objects
for select
to public
using (bucket_id = 'projects');

drop policy if exists "Public read achievements bucket" on storage.objects;
create policy "Public read achievements bucket"
on storage.objects
for select
to public
using (bucket_id = 'achievements');

alter publication supabase_realtime add table public.messages;
